on:
  push:
    branches:
      - "main"
    paths:
      - "**.rs"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    paths:
      - "**.rs"
      - "**/Cargo.toml"
      - "**/Cargo.lock"

name: Cargo Test

env:
  CARGO_TERM_COLOR: always
  CI: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      # Checkout the project
      - uses: actions/checkout@v4
      - name: Install librdkafka-dev
        run: |
          sudo apt-get update
          sudo apt-get install pkg-config librdkafka-dev cmake build-essential
      # https://nexte.st/book/test-coverage.html
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: taiki-e/install-action@nextest
      - name: Collect coverage data
        run: cargo llvm-cov nextest --all-features
